force-app/main/default/objects/Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Starter</fullName>
            </value>
            <value>
                <fullName>Main Course</fullName>
            </value>
            <value>
                <fullName>Dessert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Item_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Item_Image_Url__c</fullName>
    <label>Item Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Veg_Non_Veg__c.field-meta.xml
<CustomField>
    <fullName>Veg_Non_Veg__c</fullName>
    <label>Veg/Non Veg</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non-Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Vegan__c.field-meta.xml
<CustomField>
    <fullName>Vegan__c</fullName>
    <label>Vegan</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Veg_Non_Veg__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cafe_MenuController.cls
public without sharing class cafe_MenuController {
    @AuraEnabled(cacheable=true)
    public static Map<String,List<Item__c>> getMenuItem(){
        
            Set<String> categories = new Set<String>();
            for (item__c c : [SELECT Category__c FROM item__c]) {//look for categories and save as unique value
                categories.add(c.Category__c);
            }
            Map<String, List<Item__c>> sepratedByCategory = new Map<String, List<Item__c>>();//map to store all categories and its list as values
            for( String s: categories){
                List<item__c> tempCat = new List<item__c>();
                sepratedByCategory.put(s,tempCat);
            }
            
        List<Item__c> allItemslist= [SELECT ID, Name, Veg_Non_Veg__c,Vegan__c,Category__c,Price__c,Item_Image_Url__c,Description__c from Item__c];
        if(allItemslist!=null){
            for (Item__c eachItem : allItemslist) {
                if (sepratedByCategory.containsKey(eachItem.Category__c) ) {
                    System.debug('category is '+eachItem.Category__c+' and it matched');
                    List<Item__c> templst = sepratedByCategory.get(eachItem.Category__c);
                    templst.add(eachItem);
                    sepratedByCategory.put(eachItem.Category__c,templst);
                }
            }
        }
        
        System.debug('map to return'+sepratedByCategory);
        return sepratedByCategory;
    }

    /*
    @AuraEnabled(cacheable=true)
    public static Map<String,List<Item__c>> getMenuItem(){
        Map<String, List<Item__c>> sepratedByCategory = new Map<String, List<Item__c>>();//map to store all categories and its list as values
        List<Item__c> starterList = new List<Item__c>();// list storing starter
        List<Item__c> mainCourseList = new List<Item__c>();// list storing main course
        List<Item__c> DessertList = new List<Item__c>();// list storing dessert

        List<Item__c> allItemslist= [SELECT ID, Name, Veg_Non_Veg__c,Category__c,Price__c from Item__c];
        if(allItemslist!=null){
            for (Item__c eachItem : allItemslist) {
                if (eachItem.Category__c=='Starter') {
                    starterList.add(eachItem);//add to starterlist
                } else if(eachItem.Category__c=='Main Course'){
                    mainCourseList.add(eachItem);//add to main course list
                }else if(eachItem.Category__c=='Dessert'){
                    DessertList.add(eachItem);//add to Desssert list
                }
            }
        }
        sepratedByCategory.put('Starter',starterList);
        sepratedByCategory.put('Main Course',mainCourseList);
        sepratedByCategory.put('Dessert',DessertList);
        System.debug('map to return'+sepratedByCategory);
        return sepratedByCategory;
    }
    */
}